(()=>{
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  let recipes=[];
  const categories=['Soup','Entrée','Side','Main','Dessert','Bread','Salad','Appetizer','Breakfast','Sauce','Other'];
  function host(){return document.querySelector('#kitchenPlaceholder')}
  const withTimeout=(promise,ms=7000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timed out')),ms))]);
  const categoryChecks=(selected='')=>{const vals=String(selected||'').split(',').map(x=>x.trim());return categories.map(c=>`<label style="display:flex;align-items:center;gap:6px;padding:7px 10px;border:1px solid #d9dee7;border-radius:999px;background:#fff"><input type="checkbox" class="recipeCategoryCheck" value="${esc(c)}" ${vals.includes(c)?'checked':''} style="width:auto"> ${esc(c)}</label>`).join('')};

  function render(message=''){
    const h=host();if(!h)return;
    h.innerHTML=`<div class="subcard"><div class="section-head" style="margin-top:0;border-top:0;padding-top:0"><div><h3 style="margin:0">Food Recipes</h3><div class="muted">Create and manage kitchen recipes.</div></div><button id="addRecipeBtn" class="primary" type="button">+ Add Recipe</button></div>${message?`<div id="recipeMessage" class="muted" style="margin:10px 0">${esc(message)}</div>`:''}<div class="row" style="margin:12px 0"><input id="recipeSearch" placeholder="Search recipes…"><select id="recipeStatus"><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button id="refreshRecipes" type="button">Refresh</button></div><div id="recipeList" class="grid"></div></div><div id="recipeModal" class="modal"><div class="box" style="max-width:860px"><div class="queue-title"><h3 id="recipeModalTitle">Add Recipe</h3><button id="closeRecipe">Close</button></div><div class="grid" style="grid-template-columns:repeat(2,minmax(0,1fr));gap:12px"><label>Recipe Name<input id="recipeName"></label><label>Yield Amount<input id="recipeYield" type="number" step="0.01"></label><label>Yield Unit<input id="recipeYieldUnit" placeholder="servings, trays, pans…"></label><label>Prep Time (minutes)<input id="recipePrep" type="number"></label><label>Cook Time (minutes)<input id="recipeCook" type="number"></label></div><div style="margin-top:12px"><div style="font-weight:800;margin-bottom:7px">Categories</div><div id="recipeCategoryChecks" class="row" style="gap:7px">${categoryChecks('')}</div></div><label style="margin-top:12px">Ingredients<textarea id="recipeIngredients" rows="7" placeholder="One ingredient per line, including quantity"></textarea></label><label>Instructions<textarea id="recipeInstructions" rows="7" placeholder="Step-by-step cooking directions"></textarea></label><label>Notes<textarea id="recipeNotes" rows="4"></textarea></label><label>Recipe By<input id="recipeBy" placeholder="Name of the person who gave you the recipe"></label><label style="display:flex;align-items:center;gap:8px"><input id="recipeActive" type="checkbox" checked style="width:auto"> Active recipe</label><div class="row" style="margin-top:14px"><button id="saveRecipe" class="primary" type="button">Save Recipe</button><button id="deleteRecipe" type="button" style="display:none">Delete Recipe</button></div></div></div>`;
    h.querySelector('#addRecipeBtn').onclick=()=>open();h.querySelector('#closeRecipe').onclick=()=>h.querySelector('#recipeModal').classList.remove('show');h.querySelector('#recipeSearch').oninput=draw;h.querySelector('#recipeStatus').onchange=draw;h.querySelector('#refreshRecipes').onclick=()=>load(true);h.querySelector('#saveRecipe').onclick=save;h.querySelector('#deleteRecipe').onclick=del;draw();
  }

  async function load(showLoading=false){const h=host();if(!h)return;if(showLoading)render('Refreshing recipes…');else render('Loading saved recipes…');if(typeof db==='undefined'){render('Recipe database is not available. Please refresh the app.');return;}try{const r=await withTimeout(db.from('kitchen_recipes').select('*').order('name'));if(r.error)throw r.error;recipes=r.data||[];render(recipes.length?'':'No recipes yet. Click + Add Recipe to create your first recipe.');}catch(e){console.error('recipe load',e);render('Could not load saved recipes right now. You can still open the recipe manager; use Refresh to try again.');}}

  function draw(){const h=host();if(!h)return;const listBox=h.querySelector('#recipeList');if(!listBox)return;const q=(h.querySelector('#recipeSearch')?.value||'').toLowerCase(),st=h.querySelector('#recipeStatus')?.value||'all';const list=recipes.filter(r=>(!q||[r.name,r.category,r.ingredients,r.recipe_by].join(' ').toLowerCase().includes(q))&&(st==='all'||(st==='active'?r.active:!r.active)));listBox.innerHTML=list.length?list.map(r=>`<button type="button" class="card recipe-card" data-id="${r.id}" style="text-align:left"><div style="display:flex;justify-content:space-between;gap:8px"><b>${esc(r.name)}</b><span class="badge">${r.active?'Active':'Inactive'}</span></div><div class="muted" style="margin-top:5px">${esc(r.category||'Uncategorized')}</div><div style="margin-top:8px;font-size:13px">Yield: ${esc(r.yield_amount||'—')} ${esc(r.yield_unit||'')}</div><div style="font-size:13px">Prep: ${esc(r.prep_minutes||0)} min · Cook: ${esc(r.cook_minutes||0)} min</div>${r.recipe_by?`<div style="font-size:13px;margin-top:5px"><b>Recipe By:</b> ${esc(r.recipe_by)}</div>`:''}</button>`).join(''):'';h.querySelectorAll('.recipe-card').forEach(b=>b.onclick=()=>open(Number(b.dataset.id)));}

  function open(id){const h=host(),r=recipes.find(x=>Number(x.id)===Number(id));if(!h)return;h.querySelector('#recipeModalTitle').textContent=r?'Edit Recipe':'Add Recipe';h.querySelector('#recipeName').value=r?.name||'';h.querySelector('#recipeYield').value=r?.yield_amount??'';h.querySelector('#recipeYieldUnit').value=r?.yield_unit||'';h.querySelector('#recipePrep').value=r?.prep_minutes??'';h.querySelector('#recipeCook').value=r?.cook_minutes??'';h.querySelector('#recipeCategoryChecks').innerHTML=categoryChecks(r?.category||'');h.querySelector('#recipeIngredients').value=r?.ingredients||'';h.querySelector('#recipeInstructions').value=r?.instructions||'';h.querySelector('#recipeNotes').value=r?.notes||'';h.querySelector('#recipeBy').value=r?.recipe_by||'';h.querySelector('#recipeActive').checked=r?r.active:true;h.querySelector('#saveRecipe').dataset.id=r?.id||'';h.querySelector('#deleteRecipe').dataset.id=r?.id||'';h.querySelector('#deleteRecipe').style.display=r?'inline-block':'none';h.querySelector('#recipeModal').classList.add('show');}

  async function save(){const h=host(),btn=h?.querySelector('#saveRecipe');if(!h||!btn)return;const id=Number(btn.dataset.id)||null,name=h.querySelector('#recipeName').value.trim();if(!name)return alert('Enter a recipe name.');const selected=[...h.querySelectorAll('.recipeCategoryCheck:checked')].map(x=>x.value);const payload={name,category:selected.length?selected.join(', '):null,yield_amount:h.querySelector('#recipeYield').value?Number(h.querySelector('#recipeYield').value):null,yield_unit:h.querySelector('#recipeYieldUnit').value.trim()||null,prep_minutes:h.querySelector('#recipePrep').value?Number(h.querySelector('#recipePrep').value):null,cook_minutes:h.querySelector('#recipeCook').value?Number(h.querySelector('#recipeCook').value):null,ingredients:h.querySelector('#recipeIngredients').value.trim()||null,instructions:h.querySelector('#recipeInstructions').value.trim()||null,notes:h.querySelector('#recipeNotes').value.trim()||null,recipe_by:h.querySelector('#recipeBy').value.trim()||null,active:h.querySelector('#recipeActive').checked,updated_at:new Date().toISOString()};btn.disabled=true;btn.textContent='Saving…';try{const r=await withTimeout(id?db.from('kitchen_recipes').update(payload).eq('id',id):db.from('kitchen_recipes').insert(payload));if(r.error)throw r.error;h.querySelector('#recipeModal').classList.remove('show');await load();}catch(e){alert('Could not save recipe: '+e.message);}finally{btn.disabled=false;btn.textContent='Save Recipe';}}

  async function del(){const h=host(),id=Number(h?.querySelector('#deleteRecipe')?.dataset.id);if(!id||!confirm('Delete this recipe?'))return;try{const r=await withTimeout(db.from('kitchen_recipes').delete().eq('id',id));if(r.error)throw r.error;h.querySelector('#recipeModal').classList.remove('show');await load();}catch(e){alert('Could not delete recipe: '+e.message);}}

  document.addEventListener('click',e=>{const b=e.target.closest('[data-kitchen-page="recipes"]');if(!b)return;setTimeout(()=>load(false),30)},true);window.loadKitchenRecipes=load;
})();