(()=>{
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  let drivers=[];
  const host=()=>document.querySelector('#transportationPlaceholder');
  const daysUntil=d=>d?Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000):null;
  const expBadge=(label,date)=>{if(!date)return `<span class="badge">${label}: Not set</span>`;const n=daysUntil(date);if(n<0)return `<span class="badge" style="background:#fee2e2;color:#991b1b">${label}: EXPIRED ${esc(date)}</span>`;if(n<=30)return `<span class="badge" style="background:#fef3c7;color:#92400e">${label}: ${n} days</span>`;return `<span class="badge" style="background:#dcfce7;color:#166534">${label}: ${esc(date)}</span>`;};

  function shell(){
    const h=host();if(!h)return;
    h.innerHTML=`<div class="subcard"><div class="section-head" style="margin-top:0;border-top:0;padding-top:0"><div><h3 style="margin:0">Drivers Info</h3><div class="muted">Driver contact, license, and medical certification records.</div></div><button id="addDriverBtn" class="primary" type="button">+ Add Driver</button></div><div class="row" style="margin:12px 0"><input id="driverSearch" placeholder="Search drivers…"><select id="driverStatus"><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="expiring">Expiring / Expired</option></select></div><div id="driverList" class="grid"></div></div><div id="driverModal" class="modal"><div class="box" style="max-width:920px"><div class="queue-title"><h3 id="driverModalTitle">Add Driver</h3><button id="closeDriver">Close</button></div><div class="grid" style="grid-template-columns:repeat(3,minmax(0,1fr));gap:12px"><label>First Name<input id="dFirst"></label><label>MI<input id="dMI" maxlength="1"></label><label>Last Name<input id="dLast"></label></div><label>Address<textarea id="dAddress" rows="2"></textarea></label><div class="grid" style="grid-template-columns:repeat(3,minmax(0,1fr));gap:12px"><label>Home Phone<input id="dHome"></label><label>Cell Phone<input id="dCell"></label><label>Email<input id="dEmail" type="email"></label></div><h4>Driver's License</h4><div class="grid" style="grid-template-columns:repeat(4,minmax(0,1fr));gap:12px"><label>License #<input id="dLicense"></label><label>State<input id="dLicenseState"></label><label>Class<input id="dLicenseClass"></label><label>Expiration Date<input id="dLicenseExp" type="date"></label></div><h4>Personal / Medical</h4><div class="grid" style="grid-template-columns:repeat(3,minmax(0,1fr));gap:12px"><label>SSN Last 4<input id="dSSN4" maxlength="4" inputmode="numeric" placeholder="Last 4 only"></label><label>Medical Certificate #<input id="dMedNo"></label><label>Medical Certificate Expiration<input id="dMedExp" type="date"></label></div><label>Notes<textarea id="dNotes" rows="3"></textarea></label><label style="display:flex;align-items:center;gap:8px"><input id="dActive" type="checkbox" checked style="width:auto"> Active driver</label><div class="row" style="margin-top:14px"><button id="saveDriver" class="primary" type="button">Save Driver</button><button id="deleteDriver" type="button" style="display:none">Delete Driver</button></div></div></div>`;
    h.querySelector('#addDriverBtn').onclick=()=>open();h.querySelector('#closeDriver').onclick=()=>h.querySelector('#driverModal').classList.remove('show');h.querySelector('#driverSearch').oninput=draw;h.querySelector('#driverStatus').onchange=draw;h.querySelector('#saveDriver').onclick=save;h.querySelector('#deleteDriver').onclick=del;
  }

  async function load(){const h=host();if(!h)return;shell();h.querySelector('#driverList').innerHTML='<div class="muted">Loading drivers…</div>';if(!window.db){h.querySelector('#driverList').innerHTML='<div class="muted">Database connection unavailable.</div>';return;}try{const r=await db.from('transportation_drivers').select('*').order('last_name').order('first_name');if(r.error)throw r.error;drivers=r.data||[];draw();}catch(e){h.querySelector('#driverList').innerHTML='<div class="muted">Could not load drivers: '+esc(e.message)+'</div>';}}

  function draw(){const h=host();if(!h||!h.querySelector('#driverList'))return;const q=(h.querySelector('#driverSearch').value||'').toLowerCase(),st=h.querySelector('#driverStatus').value;const list=drivers.filter(d=>{const match=!q||[d.first_name,d.middle_initial,d.last_name,d.cell_phone,d.email,d.drivers_license_number].join(' ').toLowerCase().includes(q);const l=daysUntil(d.drivers_license_expiration),m=daysUntil(d.medical_certificate_expiration),expiring=(l!==null&&l<=30)||(m!==null&&m<=30);const status=st==='all'||(st==='active'&&d.active)||(st==='inactive'&&!d.active)||(st==='expiring'&&expiring);return match&&status;});h.querySelector('#driverList').innerHTML=list.length?list.map(d=>`<div class="card" style="text-align:left"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><b style="font-size:17px">${esc(d.first_name)} ${esc(d.middle_initial||'')} ${esc(d.last_name)}</b><div class="muted" style="margin-top:3px">${esc(d.cell_phone||d.home_phone||'No phone')}</div></div><button type="button" class="editDriver" data-id="${d.id}">Edit</button></div><div style="margin-top:10px;display:flex;gap:6px;flex-wrap:wrap">${expBadge('License',d.drivers_license_expiration)}${expBadge('Medical',d.medical_certificate_expiration)}</div>${d.email?`<div style="margin-top:10px"><a class="btn" href="mailto:${encodeURIComponent(d.email)}?subject=${encodeURIComponent('Masoras Avos Transportation')}">Email ${esc(d.email)}</a></div>`:''}<div style="margin-top:9px;font-size:13px"><b>License:</b> ${esc(d.drivers_license_number||'—')} ${esc(d.drivers_license_state||'')} ${esc(d.drivers_license_class||'')}</div><div style="font-size:13px"><b>SSN:</b> ${d.ssn_last4?'•••-••-'+esc(d.ssn_last4):'Not stored'}</div></div>`).join(''):'<div class="muted">No drivers found.</div>';h.querySelectorAll('.editDriver').forEach(b=>b.onclick=()=>open(Number(b.dataset.id)));}

  function open(id){const h=host(),d=drivers.find(x=>Number(x.id)===Number(id));h.querySelector('#driverModalTitle').textContent=d?'Edit Driver':'Add Driver';const set=(s,v)=>h.querySelector(s).value=v??'';set('#dFirst',d?.first_name);set('#dMI',d?.middle_initial);set('#dLast',d?.last_name);set('#dAddress',d?.address);set('#dHome',d?.home_phone);set('#dCell',d?.cell_phone);set('#dEmail',d?.email);set('#dLicense',d?.drivers_license_number);set('#dLicenseState',d?.drivers_license_state);set('#dLicenseClass',d?.drivers_license_class);set('#dLicenseExp',d?.drivers_license_expiration);set('#dSSN4',d?.ssn_last4);set('#dMedNo',d?.medical_certificate_number);set('#dMedExp',d?.medical_certificate_expiration);set('#dNotes',d?.notes);h.querySelector('#dActive').checked=d?d.active:true;h.querySelector('#saveDriver').dataset.id=d?.id||'';h.querySelector('#deleteDriver').dataset.id=d?.id||'';h.querySelector('#deleteDriver').style.display=d?'inline-block':'none';h.querySelector('#driverModal').classList.add('show');}

  async function save(){const h=host(),id=Number(h.querySelector('#saveDriver').dataset.id)||null,first=h.querySelector('#dFirst').value.trim(),last=h.querySelector('#dLast').value.trim(),ssn=h.querySelector('#dSSN4').value.replace(/\D/g,'');if(!first||!last)return alert('Enter first and last name.');if(ssn&&ssn.length!==4)return alert('SSN field stores the last 4 digits only.');const val=s=>h.querySelector(s).value.trim()||null;const payload={first_name:first,middle_initial:val('#dMI'),last_name:last,address:val('#dAddress'),home_phone:val('#dHome'),cell_phone:val('#dCell'),email:val('#dEmail'),drivers_license_number:val('#dLicense'),drivers_license_state:val('#dLicenseState'),drivers_license_class:val('#dLicenseClass'),drivers_license_expiration:val('#dLicenseExp'),ssn_last4:ssn||null,medical_certificate_number:val('#dMedNo'),medical_certificate_expiration:val('#dMedExp'),notes:val('#dNotes'),active:h.querySelector('#dActive').checked,updated_at:new Date().toISOString()};const r=id?await db.from('transportation_drivers').update(payload).eq('id',id):await db.from('transportation_drivers').insert(payload);if(r.error)return alert(r.error.message);h.querySelector('#driverModal').classList.remove('show');await load();}
  async function del(){const id=Number(host().querySelector('#deleteDriver').dataset.id);if(!id||!confirm('Delete this driver record?'))return;const r=await db.from('transportation_drivers').delete().eq('id',id);if(r.error)return alert(r.error.message);host().querySelector('#driverModal').classList.remove('show');await load();}
  window.loadTransportationDrivers=load;
})();