"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Tab="Dashboard"|"Products"|"Vendors"|"Orders";
type Product={id:number;name:string;sku:string;category:string;stock:number;par:number;unit:string;vendor:string;location:string};
type Vendor={id:number;name:string;contact:string;phone:string;email:string};
type Order={id:number;po:string;vendor:string;date:string;total:string;status:"Draft"|"Sent"|"Received"};
const starterProducts:Product[]=[
 {id:1,name:"Heavy-Duty Aluminum Foil",sku:"KIT-1042",category:"Kitchen Supplies",stock:6,par:12,unit:"rolls",vendor:"Restaurant Depot",location:"Dry Storage A"},
 {id:2,name:"Nitrile Gloves — Large",sku:"SAN-2201",category:"Sanitation",stock:18,par:15,unit:"boxes",vendor:"Imperial Dade",location:"Supply Room"},
 {id:3,name:"Degreaser Concentrate",sku:"CLN-0318",category:"Cleaning",stock:2,par:8,unit:"cases",vendor:"Imperial Dade",location:"Chemical Closet"},
 {id:4,name:"Walk-in Cooler Filter",sku:"MNT-4409",category:"Maintenance",stock:3,par:3,unit:"filters",vendor:"Parts Town",location:"Maintenance Cage"},
 {id:5,name:"12 oz Paper Cups",sku:"KIT-1188",category:"Kitchen Supplies",stock:22,par:20,unit:"sleeves",vendor:"Restaurant Depot",location:"Dry Storage B"}];
const starterVendors:Vendor[]=[{id:1,name:"Restaurant Depot",contact:"Sales Desk",phone:"(718) 555-0142",email:"orders@restaurantdepot.example"},{id:2,name:"Imperial Dade",contact:"David Klein",phone:"(201) 555-0178",email:"david@imperialdade.example"},{id:3,name:"Parts Town",contact:"Customer Care",phone:"(800) 555-0199",email:"orders@partstown.example"}];
const starterOrders:Order[]=[{id:1,po:"PO-2026-0084",vendor:"Imperial Dade",date:"Aug 18, 2026",total:"$482.30",status:"Sent"},{id:2,po:"PO-2026-0083",vendor:"Restaurant Depot",date:"Aug 15, 2026",total:"$1,147.92",status:"Received"},{id:3,po:"PO-2026-0085",vendor:"Parts Town",date:"Aug 19, 2026",total:"$219.00",status:"Draft"}];

export default function Home(){
 const [tab,setTab]=useState<Tab>("Dashboard"),[products,setProducts]=useState(starterProducts),[vendors,setVendors]=useState(starterVendors),[orders,setOrders]=useState(starterOrders),[search,setSearch]=useState(""),[modal,setModal]=useState<"product"|"vendor"|"order"|null>(null);
 const low=products.filter(p=>p.stock<p.par), filtered=useMemo(()=>products.filter(p=>(p.name+p.sku+p.category+p.vendor).toLowerCase().includes(search.toLowerCase())),[products,search]);
 useEffect(()=>{fetch("/api/inventory").then(r=>r.ok?r.json():null).then(d=>{if(!d)return;if(d.products?.length)setProducts(d.products);if(d.vendors?.length)setVendors(d.vendors);if(d.orders?.length)setOrders(d.orders)}).catch(()=>{})},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let record:Record<string,string|number>|undefined;if(modal==="product"){record={name:String(f.get("name")),sku:String(f.get("sku")),category:String(f.get("category")),location:String(f.get("location")),stock:Number(f.get("stock")),par:Number(f.get("par")),unit:String(f.get("unit")),vendor:String(f.get("vendor"))};setProducts(v=>[...v,{id:Date.now(),...record}])}if(modal==="vendor"){record={name:String(f.get("name")),contact:String(f.get("contact")),phone:String(f.get("phone")),email:String(f.get("email"))};setVendors(v=>[...v,{id:Date.now(),...record}])}if(modal==="order"){record={po:`PO-2026-${String(86+orders.length).padStart(4,"0")}`,vendor:String(f.get("vendor")),date:"Aug 19, 2026",total:String(f.get("total")),status:"Draft"};setOrders(v=>[{id:Date.now(),...record},...v])}const kind=modal;setModal(null);if(kind&&record)fetch("/api/inventory",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,record})}).catch(()=>{})}
 return <div className="shell"><aside><div className="brand"><b>Y</b><span><strong>YMA</strong><small>Inventory</small></span></div><nav>{(["Dashboard","Products","Vendors","Orders"] as Tab[]).map((n,i)=><button className={tab===n?"on":""} key={n} onClick={()=>setTab(n)}><i>{["⌂","□","◇","▤"][i]}</i>{n}{n==="Products"&&<em>{low.length}</em>}</button>)}</nav><div className="user"><button>⚙ Settings</button><p><b>JG</b><span><strong>Joe G.</strong><small>Administrator</small></span></p></div></aside>
 <main><header><div><h1>{tab==="Dashboard"?"Good afternoon, Joe":tab}</h1><p>{tab==="Dashboard"?"Here’s what’s happening with your inventory today.":`Manage your YMA ${tab.toLowerCase()}.`}</p></div><label className="search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search inventory..."/></label></header>
 {tab==="Dashboard"&&<><section className="stats"><Stat c="blue" i="▦" l="Total Products" v={products.length}/><Stat c="orange" i="!" l="Low Stock Items" v={low.length}/><Stat c="purple" i="▤" l="Open Orders" v={orders.filter(o=>o.status!=="Received").length}/><Stat c="green" i="$" l="Inventory Value" v="$8,426"/></section><section className="quick"><div><h2>Quick actions</h2><p>Common tasks, one click away.</p></div><button onClick={()=>setModal("product")}>＋ <span><b>Add product</b><small>Create a new item</small></span></button><button onClick={()=>setModal("order")}>▤ <span><b>Create order</b><small>Start a purchase order</small></span></button><button onClick={()=>setModal("vendor")}>◇ <span><b>Add vendor</b><small>Save a supplier</small></span></button></section><section className="cols"><Panel title="Low stock" sub="Items below their par level" action={()=>setTab("Products")}>{low.map(p=><div className="row" key={p.id}><i>□</i><span><b>{p.name}</b><small>{p.sku} · {p.location}</small></span><span className="qty"><b>{p.stock}</b><small>of {p.par} {p.unit}</small></span><Badge text="Low"/></div>)}</Panel><Panel title="Recent orders" sub="Latest purchase activity" action={()=>setTab("Orders")}>{orders.map(o=><div className="row" key={o.id}><span><b>{o.po}</b><small>{o.vendor} · {o.date}</small></span><b>{o.total}</b><Badge text={o.status}/></div>)}</Panel></section></>}
 {tab==="Products"&&<Panel title="All products" sub={`${filtered.length} inventory items`} add={()=>setModal("product")}><Table heads={["Product","Category","Location","Vendor","Stock","Status"]}>{filtered.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.sku}</small></td><td>{p.category}</td><td>{p.location}</td><td>{p.vendor}</td><td>{p.stock} / {p.par} {p.unit}</td><td><Badge text={p.stock<p.par?"Low":"In stock"}/></td></tr>)}</Table></Panel>}
 {tab==="Vendors"&&<Panel title="Vendors" sub={`${vendors.length} active suppliers`} add={()=>setModal("vendor")}><div className="cards">{vendors.map(v=><article key={v.id}><i>{v.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</i><h3>{v.name}</h3><p>{v.contact}</p><a href={`tel:${v.phone}`}>☎ {v.phone}</a><a href={`mailto:${v.email}`}>✉ {v.email}</a><div><a href={`mailto:${v.email}?subject=YMA Purchase Order`}>Email order</a><a target="_blank" href={`https://wa.me/${v.phone.replace(/\D/g,"")}`}>WhatsApp</a></div></article>)}</div></Panel>}
 {tab==="Orders"&&<Panel title="Purchase orders" sub={`${orders.length} recent orders`} add={()=>setModal("order")}><Table heads={["Order","Vendor","Date","Total","Status"]}>{orders.map(o=><tr key={o.id}><td><b>{o.po}</b></td><td>{o.vendor}</td><td>{o.date}</td><td><b>{o.total}</b></td><td><Badge text={o.status}/></td></tr>)}</Table></Panel>}
 </main>{modal&&<div className="shade" onMouseDown={()=>setModal(null)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="x" onClick={()=>setModal(null)}>×</button><h2>{modal==="product"?"Add product":modal==="vendor"?"Add vendor":"Create purchase order"}</h2><p>Enter the details below, then save.</p><div className="formgrid">{modal==="product"&&<><Field n="name" l="Product name"/><Field n="sku" l="SKU"/><Field n="category" l="Category"/><Field n="location" l="Location"/><Field n="stock" l="Current stock" t="number"/><Field n="par" l="Par level" t="number"/><Field n="unit" l="Unit"/><Select n="vendor" l="Vendor" opts={vendors.map(v=>v.name)}/></>}{modal==="vendor"&&<><Field n="name" l="Company name"/><Field n="contact" l="Contact person"/><Field n="phone" l="Phone / cell"/><Field n="email" l="Email" t="email"/></>}{modal==="order"&&<><Select n="vendor" l="Vendor" opts={vendors.map(v=>v.name)}/><Field n="total" l="Estimated total" p="$0.00"/></>}</div><footer><button type="button" onClick={()=>setModal(null)}>Cancel</button><button>Save</button></footer></form></div>}</div>}
function Stat({c,i,l,v}:{c:string;i:string;l:string;v:string|number}){return <article className="stat"><i className={c}>{i}</i><span><small>{l}</small><b>{v}</b><em>Updated today</em></span></article>}
function Panel({title,sub,action,add,children}:{title:string;sub:string;action?:()=>void;add?:()=>void;children:React.ReactNode}){return <section className="panel"><header><span><h2>{title}</h2><p>{sub}</p></span>{(action||add)&&<button onClick={action||add}>{add?"＋ Add new":"View all →"}</button>}</header>{children}</section>}
function Table({heads,children}:{heads:string[];children:React.ReactNode}){return <div className="table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Badge({text}:{text:string}){return <em className={`badge ${text.toLowerCase().replace(" ","")}`}>{text}</em>}
function Field({n,l,t="text",p}:{n:string;l:string;t?:string;p?:string}){return <label>{l}<input name={n} type={t} placeholder={p} required/></label>}
function Select({n,l,opts}:{n:string;l:string;opts:string[]}){return <label>{l}<select name={n}>{opts.map(o=><option key={o}>{o}</option>)}</select></label>}
